name = "together-backend"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
# Add a secure JWT Secret
JWT_SECRET = "super_private_together_key_secret_2026"

# User credentials as JSON array
# Format: [{"username":"...","password":"..."}]
USERS = '[{"username":"zain","password":"zain-aqdas-6464"},{"username":"hadi","password":"hadia-khan-6464"}]'

[[kv_namespaces]]
binding = "TOGETHER_KV"
id = "a216c93ec7af47b2a27feba002164706"

[[durable_objects.bindings]]
name = "TOGETHER_SESSION"
class_name = "TogetherSessionManager"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TogetherSessionManager"]
